blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/openhims/rustcare-engine/discussions
    about: Ask questions, share ideas, and discuss OpenHIMS
  - name: 🗨️ Community Discord
    url: https://discord.gg/openhims
    about: Join our community for real-time chat and support
  - name: 📚 Documentation
    url: https://docs.openhims.org
    about: Read the official OpenHIMS documentation
  - name: 🔒 Security Issue
    url: https://github.com/openhims/rustcare-engine/security/advisories/new
    about: Report security vulnerabilities privately (do not use public issues)
  - name: 💼 Commercial Support
    url: https://openhims.org/commercial
    about: Get professional support, consulting, or managed services

